-- Browser-facing API for the standalone Wi-Fi voucher module.
-- Password tables remain in the private wifi_voucher schema. The frontend can
-- only call the explicitly granted RPC functions below after Supabase Auth.

create table if not exists wifi_voucher.memberships (
    user_id uuid not null references auth.users(id) on delete cascade,
    hotel_id text not null references wifi_voucher.hotels(id) on delete cascade,
    role text not null default 'operator'
        check (role in ('admin', 'operator', 'viewer')),
    active boolean not null default true,
    display_name text,
    created_at timestamptz not null default now(),
    primary key (user_id, hotel_id)
);

create table if not exists wifi_voucher.audit_events (
    id bigint generated by default as identity primary key,
    hotel_id text not null references wifi_voucher.hotels(id) on delete cascade,
    user_id uuid references auth.users(id) on delete set null,
    action text not null,
    entity_type text not null,
    entity_id text,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_memberships_hotel_active
    on wifi_voucher.memberships(hotel_id, active, user_id);
create index if not exists idx_audit_hotel_created
    on wifi_voucher.audit_events(hotel_id, created_at desc);

alter table wifi_voucher.memberships enable row level security;
alter table wifi_voucher.audit_events enable row level security;

revoke all on table wifi_voucher.memberships from public, anon, authenticated;
revoke all on table wifi_voucher.audit_events from public, anon, authenticated;

create or replace function wifi_voucher.require_role(
    p_hotel_id text,
    p_roles text[] default array['admin', 'operator', 'viewer']::text[]
) returns text
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_role text;
begin
    if auth.uid() is null then
        raise exception using errcode = '42501', message = 'Требуется авторизация.';
    end if;

    select m.role into v_role
    from wifi_voucher.memberships m
    where m.user_id = auth.uid()
      and m.hotel_id = p_hotel_id
      and m.active;

    if v_role is null or not (v_role = any(p_roles)) then
        raise exception using errcode = '42501', message = 'Нет доступа к этому отелю.';
    end if;
    return v_role;
end;
$$;

revoke all on function wifi_voucher.require_role(text, text[]) from public, anon, authenticated;

create or replace function wifi_voucher.stats_json(p_hotel_id text)
returns jsonb
language sql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
    select jsonb_build_object(
        'available', count(*) filter (where p.status = 'available'),
        'reserved', count(*) filter (where p.status = 'reserved'),
        'used', count(*) filter (where p.status = 'used'),
        'total', count(*)
    )
    from wifi_voucher.passwords p
    where p.hotel_id = p_hotel_id;
$$;

revoke all on function wifi_voucher.stats_json(text) from public, anon, authenticated;

create or replace function wifi_voucher.release_stale(p_hotel_id text)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_count integer;
begin
    update wifi_voucher.generations g
    set status = 'failed',
        error = coalesce(g.error, 'Reservation expired'),
        completed_at = now()
    where g.status = 'reserved'
      and g.id in (
          select distinct p.batch_id
          from wifi_voucher.passwords p
          where p.hotel_id = p_hotel_id
            and p.status = 'reserved'
            and p.reserved_at < now() - interval '20 minutes'
            and p.batch_id is not null
      );

    update wifi_voucher.passwords p
    set status = 'available', batch_id = null, reserved_at = null
    where p.hotel_id = p_hotel_id
      and p.status = 'reserved'
      and p.reserved_at < now() - interval '20 minutes';
    get diagnostics v_count = row_count;
    return v_count;
end;
$$;

revoke all on function wifi_voucher.release_stale(text) from public, anon, authenticated;

create or replace function public.voucher_bootstrap()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_membership wifi_voucher.memberships%rowtype;
    v_hotel wifi_voucher.hotels%rowtype;
begin
    if auth.uid() is null then
        raise exception using errcode = '42501', message = 'Требуется авторизация.';
    end if;

    select m.* into v_membership
    from wifi_voucher.memberships m
    where m.user_id = auth.uid() and m.active
    order by m.created_at
    limit 1;

    if v_membership.user_id is null then
        raise exception using errcode = '42501', message = 'Учётной записи ещё не выдан доступ.';
    end if;

    select h.* into v_hotel from wifi_voucher.hotels h where h.id = v_membership.hotel_id;
    perform wifi_voucher.release_stale(v_hotel.id);

    return jsonb_build_object(
        'module', jsonb_build_object(
            'id', 'wifi-voucher',
            'name', 'Wi-Fi пароли',
            'version', '2.0.0',
            'mode', 'standalone',
            'capabilities', jsonb_build_array(
                'passwords.read', 'passwords.import', 'passwords.edit',
                'passwords.issue', 'passwords.delete', 'vouchers.generate'
            )
        ),
        'hotel', jsonb_build_object('id', v_hotel.id, 'name', v_hotel.name),
        'membership', jsonb_build_object(
            'role', v_membership.role,
            'display_name', v_membership.display_name,
            'email', auth.jwt() ->> 'email'
        ),
        'stats', wifi_voucher.stats_json(v_hotel.id)
    );
end;
$$;

create or replace function public.voucher_list(
    p_hotel_id text,
    p_limit integer default 25,
    p_offset integer default 0,
    p_search text default ''
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_items jsonb;
begin
    perform wifi_voucher.require_role(p_hotel_id);
    perform wifi_voucher.release_stale(p_hotel_id);

    if p_limit < 1 or p_limit > 100 or p_offset < 0 then
        raise exception using errcode = '22023', message = 'Некорректная пагинация.';
    end if;

    select coalesce(jsonb_agg(to_jsonb(q) order by q.id), '[]'::jsonb) into v_items
    from (
        select p.id, p.password, p.created_at
        from wifi_voucher.passwords p
        where p.hotel_id = p_hotel_id
          and p.status = 'available'
          and (coalesce(btrim(p_search), '') = '' or p.password ilike '%' || btrim(p_search) || '%')
        order by p.id
        limit p_limit offset p_offset
    ) q;

    return jsonb_build_object(
        'items', v_items,
        'stats', wifi_voucher.stats_json(p_hotel_id)
    );
end;
$$;

create or replace function public.voucher_import_preview(
    p_hotel_id text,
    p_passwords text[]
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_raw text;
    v_value text;
    v_seen text[] := array[]::text[];
    v_items jsonb := '[]'::jsonb;
    v_recognized integer := 0;
    v_new integer := 0;
    v_duplicates integer := 0;
    v_invalid integer := 0;
    v_status text;
    v_reason text;
begin
    perform wifi_voucher.require_role(p_hotel_id, array['admin', 'operator']);
    if coalesce(cardinality(p_passwords), 0) > 5000 then
        raise exception using errcode = '22023', message = 'За один раз можно проверить не более 5000 паролей.';
    end if;

    foreach v_raw in array coalesce(p_passwords, array[]::text[]) loop
        v_value := btrim(coalesce(v_raw, ''));
        v_status := null;
        v_reason := null;

        if v_value = '' or lower(v_value) in ('password', 'пароль') or char_length(v_value) > 256 then
            v_invalid := v_invalid + 1;
            v_status := 'invalid';
            v_reason := 'Пустая строка, заголовок или слишком длинное значение';
        else
            v_recognized := v_recognized + 1;
            if v_value = any(v_seen) then
                v_duplicates := v_duplicates + 1;
                v_status := 'duplicate';
                v_reason := 'Повтор внутри импортируемой партии';
            elsif exists (
                select 1 from wifi_voucher.passwords p
                where p.hotel_id = p_hotel_id and p.password = v_value
            ) then
                v_duplicates := v_duplicates + 1;
                v_status := 'duplicate';
                v_reason := 'Уже есть в базе';
            else
                v_new := v_new + 1;
                v_status := 'new';
            end if;
            if not (v_value = any(v_seen)) then
                v_seen := array_append(v_seen, v_value);
            end if;
        end if;

        v_items := v_items || jsonb_build_array(jsonb_build_object(
            'value', coalesce(v_raw, ''),
            'normalized', case when v_status = 'invalid' then null else v_value end,
            'status', v_status,
            'reason', v_reason
        ));
    end loop;

    return jsonb_build_object(
        'items', v_items,
        'summary', jsonb_build_object(
            'recognized', v_recognized,
            'new', v_new,
            'duplicates', v_duplicates,
            'invalid', v_invalid
        )
    );
end;
$$;

create or replace function public.voucher_import(
    p_hotel_id text,
    p_passwords text[]
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_raw text;
    v_value text;
    v_added integer := 0;
    v_duplicates integer := 0;
    v_invalid integer := 0;
begin
    perform wifi_voucher.require_role(p_hotel_id, array['admin', 'operator']);
    if coalesce(cardinality(p_passwords), 0) < 1 or cardinality(p_passwords) > 5000 then
        raise exception using errcode = '22023', message = 'Передайте от 1 до 5000 паролей.';
    end if;

    foreach v_raw in array p_passwords loop
        v_value := btrim(coalesce(v_raw, ''));
        if v_value = '' or lower(v_value) in ('password', 'пароль') or char_length(v_value) > 256 then
            v_invalid := v_invalid + 1;
        else
            insert into wifi_voucher.passwords(hotel_id, password)
            values (p_hotel_id, v_value)
            on conflict (hotel_id, password) do nothing;
            if found then v_added := v_added + 1;
            else v_duplicates := v_duplicates + 1;
            end if;
        end if;
    end loop;

    insert into wifi_voucher.audit_events(hotel_id, user_id, action, entity_type, details)
    values (p_hotel_id, auth.uid(), 'passwords.import', 'password',
            jsonb_build_object('added', v_added, 'duplicates', v_duplicates, 'invalid', v_invalid));

    return jsonb_build_object(
        'added', v_added,
        'duplicates', v_duplicates,
        'invalid', v_invalid,
        'stats', wifi_voucher.stats_json(p_hotel_id)
    );
end;
$$;

create or replace function public.voucher_update(
    p_hotel_id text,
    p_id bigint,
    p_password text
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_value text := btrim(coalesce(p_password, ''));
begin
    perform wifi_voucher.require_role(p_hotel_id, array['admin', 'operator']);
    if v_value = '' or lower(v_value) in ('password', 'пароль') or char_length(v_value) > 256 then
        raise exception using errcode = '22023', message = 'Некорректный пароль.';
    end if;

    update wifi_voucher.passwords p
    set password = v_value
    where p.id = p_id and p.hotel_id = p_hotel_id and p.status = 'available';
    if not found then
        raise exception using errcode = 'P0002', message = 'Доступный пароль не найден.';
    end if;

    insert into wifi_voucher.audit_events(hotel_id, user_id, action, entity_type, entity_id)
    values (p_hotel_id, auth.uid(), 'password.update', 'password', p_id::text);
    return jsonb_build_object('updated', true, 'stats', wifi_voucher.stats_json(p_hotel_id));
exception
    when unique_violation then
        raise exception using errcode = '23505', message = 'Такой пароль уже есть в базе.';
end;
$$;

create or replace function public.voucher_issue(
    p_hotel_id text,
    p_ids bigint[]
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_requested integer := coalesce(cardinality(p_ids), 0);
    v_unique integer;
    v_available integer;
    v_passwords jsonb;
begin
    perform wifi_voucher.require_role(p_hotel_id, array['admin', 'operator']);
    if v_requested < 1 or v_requested > 1000 then
        raise exception using errcode = '22023', message = 'Выберите от 1 до 1000 паролей.';
    end if;
    select count(distinct x) into v_unique from unnest(p_ids) x;
    if v_unique <> v_requested then
        raise exception using errcode = '22023', message = 'Список содержит повторяющиеся идентификаторы.';
    end if;

    perform 1 from wifi_voucher.passwords p
    where p.hotel_id = p_hotel_id and p.id = any(p_ids)
    for update;
    select count(*) into v_available
    from wifi_voucher.passwords p
    where p.hotel_id = p_hotel_id and p.id = any(p_ids) and p.status = 'available';
    if v_available <> v_requested then
        raise exception using errcode = 'P0001', message = 'Один или несколько паролей уже недоступны. Обновите таблицу.';
    end if;

    select jsonb_agg(p.password order by selected.ord) into v_passwords
    from unnest(p_ids) with ordinality selected(id, ord)
    join wifi_voucher.passwords p on p.id = selected.id and p.hotel_id = p_hotel_id;

    update wifi_voucher.passwords p
    set status = 'used', used_at = now(), batch_id = null, reserved_at = null
    where p.hotel_id = p_hotel_id and p.id = any(p_ids);

    insert into wifi_voucher.audit_events(hotel_id, user_id, action, entity_type, details)
    values (p_hotel_id, auth.uid(), 'passwords.issue', 'password', jsonb_build_object('count', v_requested));
    return jsonb_build_object(
        'issued', v_requested,
        'passwords', v_passwords,
        'stats', wifi_voucher.stats_json(p_hotel_id)
    );
end;
$$;

create or replace function public.voucher_delete(
    p_hotel_id text,
    p_ids bigint[]
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_deleted integer;
begin
    perform wifi_voucher.require_role(p_hotel_id, array['admin']);
    if coalesce(cardinality(p_ids), 0) < 1 or cardinality(p_ids) > 1000 then
        raise exception using errcode = '22023', message = 'Выберите от 1 до 1000 паролей.';
    end if;
    delete from wifi_voucher.passwords p
    where p.hotel_id = p_hotel_id and p.id = any(p_ids) and p.status = 'available';
    get diagnostics v_deleted = row_count;

    insert into wifi_voucher.audit_events(hotel_id, user_id, action, entity_type, details)
    values (p_hotel_id, auth.uid(), 'passwords.delete', 'password', jsonb_build_object('count', v_deleted));
    return jsonb_build_object('deleted', v_deleted, 'stats', wifi_voucher.stats_json(p_hotel_id));
end;
$$;

create or replace function public.voucher_reserve(
    p_hotel_id text,
    p_ru integer,
    p_en integer
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_total integer := coalesce(p_ru, 0) + coalesce(p_en, 0);
    v_batch uuid := gen_random_uuid();
    v_ids bigint[];
    v_passwords jsonb;
begin
    perform wifi_voucher.require_role(p_hotel_id, array['admin', 'operator']);
    if coalesce(p_ru, 0) < 0 or coalesce(p_en, 0) < 0 or v_total < 1 or v_total > 500 then
        raise exception using errcode = '22023', message = 'Укажите от 1 до 500 карточек.';
    end if;
    perform wifi_voucher.release_stale(p_hotel_id);

    select array_agg(q.id order by q.id) into v_ids
    from (
        select p.id
        from wifi_voucher.passwords p
        where p.hotel_id = p_hotel_id and p.status = 'available'
        order by p.id
        for update skip locked
        limit v_total
    ) q;

    if coalesce(cardinality(v_ids), 0) <> v_total then
        raise exception using errcode = 'P0001',
            message = format('Недостаточно доступных паролей: нужно %s.', v_total);
    end if;

    update wifi_voucher.passwords p
    set status = 'reserved', batch_id = v_batch, reserved_at = now()
    where p.id = any(v_ids);

    insert into wifi_voucher.generations(id, hotel_id, ru_count, en_count, total_count, status)
    values (v_batch, p_hotel_id, p_ru, p_en, v_total, 'reserved');

    select jsonb_agg(p.password order by p.id) into v_passwords
    from wifi_voucher.passwords p where p.id = any(v_ids);

    insert into wifi_voucher.audit_events(hotel_id, user_id, action, entity_type, entity_id, details)
    values (p_hotel_id, auth.uid(), 'generation.reserve', 'generation', v_batch::text,
            jsonb_build_object('ru', p_ru, 'en', p_en, 'total', v_total));

    return jsonb_build_object(
        'batch_id', v_batch,
        'passwords', v_passwords,
        'ru_count', p_ru,
        'en_count', p_en,
        'stats', wifi_voucher.stats_json(p_hotel_id)
    );
end;
$$;

create or replace function public.voucher_generation_commit(
    p_hotel_id text,
    p_batch_id uuid
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_count integer;
begin
    perform wifi_voucher.require_role(p_hotel_id, array['admin', 'operator']);
    perform 1 from wifi_voucher.generations g
    where g.id = p_batch_id and g.hotel_id = p_hotel_id and g.status = 'reserved'
    for update;
    if not found then
        raise exception using errcode = 'P0002', message = 'Резерв генерации не найден.';
    end if;

    update wifi_voucher.passwords p
    set status = 'used', used_at = now(), reserved_at = null
    where p.hotel_id = p_hotel_id and p.batch_id = p_batch_id and p.status = 'reserved';
    get diagnostics v_count = row_count;
    update wifi_voucher.generations g
    set status = 'completed', completed_at = now(), error = null
    where g.id = p_batch_id;
    insert into wifi_voucher.audit_events(hotel_id, user_id, action, entity_type, entity_id, details)
    values (p_hotel_id, auth.uid(), 'generation.commit', 'generation', p_batch_id::text,
            jsonb_build_object('count', v_count));
    return jsonb_build_object('committed', v_count, 'stats', wifi_voucher.stats_json(p_hotel_id));
end;
$$;

create or replace function public.voucher_generation_release(
    p_hotel_id text,
    p_batch_id uuid,
    p_error text default null
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, wifi_voucher
as $$
declare
    v_count integer;
begin
    perform wifi_voucher.require_role(p_hotel_id, array['admin', 'operator']);
    update wifi_voucher.passwords p
    set status = 'available', batch_id = null, reserved_at = null
    where p.hotel_id = p_hotel_id and p.batch_id = p_batch_id and p.status = 'reserved';
    get diagnostics v_count = row_count;
    update wifi_voucher.generations g
    set status = 'failed', error = left(p_error, 1000), completed_at = now()
    where g.id = p_batch_id and g.hotel_id = p_hotel_id and g.status = 'reserved';
    insert into wifi_voucher.audit_events(hotel_id, user_id, action, entity_type, entity_id, details)
    values (p_hotel_id, auth.uid(), 'generation.release', 'generation', p_batch_id::text,
            jsonb_build_object('count', v_count));
    return jsonb_build_object('released', v_count, 'stats', wifi_voucher.stats_json(p_hotel_id));
end;
$$;

do $$
declare
    fn regprocedure;
begin
    foreach fn in array array[
        'public.voucher_bootstrap()'::regprocedure,
        'public.voucher_list(text,integer,integer,text)'::regprocedure,
        'public.voucher_import_preview(text,text[])'::regprocedure,
        'public.voucher_import(text,text[])'::regprocedure,
        'public.voucher_update(text,bigint,text)'::regprocedure,
        'public.voucher_issue(text,bigint[])'::regprocedure,
        'public.voucher_delete(text,bigint[])'::regprocedure,
        'public.voucher_reserve(text,integer,integer)'::regprocedure,
        'public.voucher_generation_commit(text,uuid)'::regprocedure,
        'public.voucher_generation_release(text,uuid,text)'::regprocedure
    ] loop
        execute format('revoke all on function %s from public, anon', fn);
        execute format('grant execute on function %s to authenticated', fn);
    end loop;
end;
$$;

notify pgrst, 'reload schema';
